"""Pure safety primitives for Windows PowerPoint automation."""

from .assets import (
    AssetChoice,
    AssetIntent,
    AssetPolicy,
    AssetRecord,
    AssetSession,
    choose_asset,
    load_asset_policy,
    read_raster_dimensions,
)
from .com_session import dispatch_powerpoint, macro_security
from .cli import build_dry_run_result, collect_requested_actions, emit_result, parse_args
from .capacity import split_slide
from .deck_plan import (
    ContentBlock,
    DeckPlan,
    DeckPlanValidationError,
    ProjectIntent,
    SlideIntent,
    compile_deck_plan,
    load_deck_plan,
    validate_deck_plan,
)
from .errors import ComSessionError, OutputPolicyError, WindowPptxError
from .layouts import (
    GridDefinition,
    LayoutCapacity,
    LayoutRegistry,
    ResolvedLayout,
    SlideSize,
    load_components,
    load_layout_registry,
    resolve_layout,
    validate_registry_bundle,
)
from .models import CandidateResult, OutputPolicy, PowerPointHandle
from .output_policy import calculate_export_size, validate_output_policy
from .registry import Archetype, RegistryError, load_archetypes, resolve_archetype
from .recording_com import RecordingCall, RecordingPresentation
from .quality import (
    HARD_GATE_CODES,
    QUALITY_LAYERS,
    LayerSnapshot,
    QualityFinding,
    QualityGateError,
    QualityReport,
    RepairAction,
    RepairLog,
    RepairPass,
    finalize_quality_report,
    inspect_quality,
    repair_quality,
    write_quality_artifacts,
)
from .renderer import PowerPointRenderer, RenderError, RenderReport
from .render_plan import (
    AssetBinding,
    ChartSeries,
    ChartSpec,
    DiagramNode,
    DiagramSpec,
    RenderFinding,
    RenderObject,
    RenderPlan,
    RenderPlanError,
    RenderSlide,
    TableSpec,
    build_render_plan,
    compile_render_plan,
    inches_to_points,
    load_asset_bindings,
    validate_render_plan,
)
from .rules import CandidateScore, DecisionTrace, rank_page_families
from .runner import PipelineResult, execute_render_plan, run_render_pipeline
from .transaction import (
    PartialSaveError,
    SourceIntegrityError,
    TransactionError,
    candidate_path_for,
    save_candidate,
    sha256_file,
    validate_ooxml_package,
)
from .themes import (
    BrandOverrides,
    ResolvedTheme,
    contrast_ratio,
    load_themes,
    resolve_theme,
    select_theme,
)

__all__ = [
    "Archetype",
    "AssetChoice",
    "AssetBinding",
    "AssetIntent",
    "AssetPolicy",
    "AssetRecord",
    "AssetSession",
    "BrandOverrides",
    "ChartSeries",
    "ChartSpec",
    "ComSessionError",
    "ContentBlock",
    "CandidateResult",
    "CandidateScore",
    "DeckPlan",
    "DeckPlanValidationError",
    "DecisionTrace",
    "DiagramNode",
    "DiagramSpec",
    "GridDefinition",
    "HARD_GATE_CODES",
    "LayoutCapacity",
    "LayoutRegistry",
    "LayerSnapshot",
    "OutputPolicy",
    "OutputPolicyError",
    "PowerPointHandle",
    "PowerPointRenderer",
    "QUALITY_LAYERS",
    "ProjectIntent",
    "RegistryError",
    "RecordingCall",
    "RecordingPresentation",
    "QualityFinding",
    "QualityGateError",
    "QualityReport",
    "RenderError",
    "RenderFinding",
    "RenderObject",
    "RenderPlan",
    "RenderPlanError",
    "RenderReport",
    "RenderSlide",
    "RepairAction",
    "RepairLog",
    "RepairPass",
    "ResolvedLayout",
    "ResolvedTheme",
    "SlideIntent",
    "SlideSize",
    "PartialSaveError",
    "SourceIntegrityError",
    "TransactionError",
    "TableSpec",
    "WindowPptxError",
    "build_dry_run_result",
    "build_render_plan",
    "calculate_export_size",
    "candidate_path_for",
    "collect_requested_actions",
    "compile_deck_plan",
    "compile_render_plan",
    "contrast_ratio",
    "choose_asset",
    "dispatch_powerpoint",
    "emit_result",
    "finalize_quality_report",
    "execute_render_plan",
    "macro_security",
    "inches_to_points",
    "inspect_quality",
    "load_archetypes",
    "load_asset_policy",
    "load_asset_bindings",
    "load_components",
    "load_deck_plan",
    "load_layout_registry",
    "load_themes",
    "parse_args",
    "save_candidate",
    "rank_page_families",
    "read_raster_dimensions",
    "repair_quality",
    "write_quality_artifacts",
    "run_render_pipeline",
    "resolve_archetype",
    "resolve_layout",
    "resolve_theme",
    "sha256_file",
    "select_theme",
    "validate_ooxml_package",
    "validate_output_policy",
    "validate_deck_plan",
    "validate_registry_bundle",
    "validate_render_plan",
    "split_slide",
    "PipelineResult",
]
