"""Resolve semantic AssetPlan intents into governed renderer bindings.

AssetPlan is deliberately semantic; this module is the transaction boundary
that freezes selected/generated bytes, records provenance, and chooses a
declared native fallback before layout resolution. Facts never enter image
prompts or generated pixels.
"""

from __future__ import annotations

import hashlib
import io
from dataclasses import dataclass, replace
from datetime import date
from pathlib import Path
from typing import Callable, Mapping

from PIL import Image

from .agnes_direct import GeneratedAsset
from .assets import AssetRecord, load_asset_policy, read_raster_dimensions
from .design_packs import DesignPack
from .render_plan import AssetBinding
from .visual_plan import AssetPlan, PlannedAsset


class AssetMaterializationError(ValueError):
    """An asset could not be frozen without violating the governed contract."""


@dataclass(frozen=True)
class MaterializedAsset:
    asset_id: str
    slide_id: str
    status: str
    required: bool
    source_kind: str
    fallback: str
    reason: str | None
    byte_sha256: str | None
    path: Path | None
    crop_mode: str
    focal_safe_zone: str
    replaceable: bool
    provider_route: str | None = None
    provider_model: str | None = None
    provider_manifest: Mapping[str, object] | None = None

    def to_dict(self) -> dict[str, object]:
        return {
            "asset_id": self.asset_id,
            "slide_id": self.slide_id,
            "status": self.status,
            "required": self.required,
            "source_kind": self.source_kind,
            "fallback": self.fallback,
            "reason": self.reason,
            "byte_sha256": self.byte_sha256,
            "path": str(self.path) if self.path is not None else None,
            "crop_mode": self.crop_mode,
            "focal_safe_zone": self.focal_safe_zone,
            "replaceable": self.replaceable,
            "provider_route": self.provider_route,
            "provider_model": self.provider_model,
            "provider_manifest": (
                dict(self.provider_manifest)
                if self.provider_manifest is not None
                else None
            ),
        }


@dataclass(frozen=True)
class AssetMaterialization:
    asset_plan: AssetPlan
    bindings: Mapping[str, AssetBinding]
    entries: tuple[MaterializedAsset, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "schema_version": "1.0",
            "design_pack_id": self.asset_plan.design_pack_id,
            "entries": [entry.to_dict() for entry in self.entries],
        }

    def assert_release_ready(self) -> None:
        blocked = [
            entry.asset_id
            for entry in self.entries
            if entry.required and entry.status in {"planned", "rejected"}
        ]
        if blocked:
            raise AssetMaterializationError(
                "required assets are not release-ready: " + ", ".join(blocked)
            )


ImageGenerator = Callable[..., GeneratedAsset]


def _image_suffix(payload: bytes) -> str:
    if payload.startswith(b"\x89PNG\r\n\x1a\n"):
        return ".png"
    if payload.startswith(b"\xff\xd8"):
        return ".jpg"
    raise AssetMaterializationError(
        "generated asset must be a renderer-supported PNG or JPEG"
    )


def _prompt(asset: PlannedAsset, design_pack: DesignPack) -> str:
    art = design_pack.art_direction
    art_id = art.id if art is not None else design_pack.id
    palette = (
        ", ".join(f"{key} #{value}" for key, value in art.palette_roles.items())
        if art is not None
        else (
            f"primary #{design_pack.theme.primary}, "
            f"accent #{design_pack.theme.accent}"
        )
    )
    motif_direction = {
        "knowledge-wayfinding": (
            "Use a premium abstract editorial still life made from architectural "
            "paper layers, translucent portals, sculptural route markers, and subtle "
            "concentric navigation rings. Do not depict screens, devices, documents, "
            "signage, interfaces, people, faces, or other objects that commonly "
            "produce pseudo-lettering. Use warm ivory light, analogous teal and "
            "deep green, and one muted gold accent. Preserve a broad calm light "
            "region for oversized editorial typography. Keep this repeatable motif "
            "across cover, dividers, and close. Avoid generic corporate stock poses, "
            "literal buildings, sci-fi dashboards, ornamental clutter, and "
            "fragmented rainbow palettes. "
        ),
        "luminous-product-stage": (
            "Represent an AI work assistant as an abstract luminous system of "
            "connected modules, a controlled signal pulse, and one clear orchestration "
            "path on a dark premium launch stage. Use violet and restrained teal "
            "light with deep graphite surfaces. Do not depict perfume, cosmetics, "
            "bottles, skincare, consumer packaging, household objects, people, "
            "screens, dashboards, or device mockups. The image must read as software "
            "intelligence and workflow coordination, not a physical retail product. "
            "Keep one repeatable pulse-and-orbit motif across the visual family. "
        ),
        "evidence-margin": (
            "Use an editorial research composition made from precise datum lines, "
            "evidence brackets, measured geometric fields, and one restrained "
            "annotation point on warm ivory paper. Do not depict people, portraits, "
            "office scenes, consumer products, screens, dashboards, or decorative "
            "stock-photo metaphors. Preserve a calm evidence-led tone with teal ink "
            "and one muted gold signal. "
        ),
    }.get(
        art_id,
        "Use a coherent project-specific visual metaphor and repeatable geometric "
        "motif suitable for a multi-page executive presentation. ",
    )
    return (
        f"Create one premium editorial business visual for {asset.purpose}. "
        f"Art direction: {art_id}. Palette: {palette}. "
        f"{motif_direction}"
        "Use layered depth, a clear focal point, generous intentional negative "
        "space, and a crop-safe 16:9 composition. Keep important imagery away "
        "from the outer 12% and leave a calm text-safe region. "
        "No factual data, no numbers, no charts, no text, no logo, no watermark."
    )


def _generated_binding(
    asset: PlannedAsset,
    generated: GeneratedAsset,
    output_dir: Path,
    *,
    retrieved_at: str,
) -> tuple[AssetBinding, Path, str]:
    suffix = _image_suffix(generated.image_bytes)
    output_dir.mkdir(parents=True, exist_ok=True)
    source_path = (output_dir / f"{asset.id}.source{suffix}").resolve()
    source_path.write_bytes(generated.image_bytes)
    source_sha256 = hashlib.sha256(generated.image_bytes).hexdigest()
    declared_hash = generated.manifest.get("output_sha256")
    if declared_hash != source_sha256:
        source_path.unlink(missing_ok=True)
        raise AssetMaterializationError(
            f"generated asset hash mismatch for {asset.id}"
        )
    width, height = read_raster_dimensions(source_path)
    minimum = load_asset_policy().minimum_raster_short_edge_px
    path = source_path
    if min(width, height) < minimum:
        scale = minimum / min(width, height)
        target = (round(width * scale), round(height * scale))
        with Image.open(io.BytesIO(generated.image_bytes)) as image:
            normalized = image.convert("RGB").resize(target, Image.Resampling.LANCZOS)
            path = (output_dir / f"{asset.id}.png").resolve()
            normalized.save(path, format="PNG", optimize=True)
        width, height = read_raster_dimensions(path)
    byte_sha256 = hashlib.sha256(path.read_bytes()).hexdigest()
    return (
        AssetBinding(
            path=path,
            record=AssetRecord(
                id=asset.id,
                kind=asset.kind,
                style="generated-editorial",
                aspect_ratio=width / height,
                quality=95,
                source=generated.route_id,
                license="user-authorized-generated-asset",
                retrieved_at=retrieved_at,
                width_px=width,
                height_px=height,
            ),
        ),
        path,
        byte_sha256,
    )


def materialize_asset_plan(
    asset_plan: AssetPlan,
    design_pack: DesignPack,
    *,
    required_asset_ids: frozenset[str] = frozenset(),
    provided_bindings: Mapping[str, AssetBinding] | None = None,
    image_generator: ImageGenerator | None = None,
    output_dir: Path | str | None = None,
    retrieved_at: str | None = None,
) -> AssetMaterialization:
    """Resolve every planned intent without leaving ambiguous release state."""

    if asset_plan.design_pack_id != design_pack.id:
        raise AssetMaterializationError("AssetPlan DesignPack identity drifted")
    supplied = dict(provided_bindings or {})
    frozen_dir = Path(output_dir).resolve() if output_dir is not None else None
    retrieval_date = retrieved_at or date.today().isoformat()
    bindings: dict[str, AssetBinding] = {}
    updated: list[PlannedAsset] = []
    entries: list[MaterializedAsset] = []
    crop_mode = (
        design_pack.art_direction.image_crop
        if design_pack.art_direction is not None
        else "cover"
    )
    for asset in asset_plan.assets:
        required = asset.id in required_asset_ids
        binding = supplied.get(asset.id)
        status: str
        source_kind: str
        reason: str | None = None
        byte_sha256: str | None = None
        path: Path | None = None
        provider_route: str | None = None
        provider_model: str | None = None
        provider_manifest: Mapping[str, object] | None = None
        if binding is not None:
            path = binding.path.resolve()
            if not path.is_file():
                raise AssetMaterializationError(
                    f"provided asset is missing: {asset.id}"
                )
            bindings[asset.id] = binding
            byte_sha256 = hashlib.sha256(path.read_bytes()).hexdigest()
            status = "resolved"
            source_kind = "provided"
        elif asset.editable:
            status = "native-materialized"
            source_kind = "native"
        elif image_generator is not None and frozen_dir is not None:
            try:
                generated = image_generator(prompt=_prompt(asset, design_pack))
                binding, path, byte_sha256 = _generated_binding(
                    asset,
                    generated,
                    frozen_dir,
                    retrieved_at=retrieval_date,
                )
                bindings[asset.id] = binding
                status = "generated"
                source_kind = "generated"
                provider_route = generated.route_id
                provider_model = generated.model
                provider_manifest = {
                    **dict(generated.manifest),
                    "materialized_output_sha256": byte_sha256,
                    "materialized_dimensions": [
                        binding.record.width_px,
                        binding.record.height_px,
                    ],
                    "normalization": (
                        "lanczos-minimum-short-edge"
                        if generated.manifest.get("output_sha256")
                        != byte_sha256
                        else "none"
                    ),
                }
            except Exception as exc:
                status = "fallback"
                source_kind = "native"
                reason = f"GENERATION_FAILED:{type(exc).__name__}"
        else:
            status = "fallback"
            source_kind = "native"
            reason = "NO_GOVERNED_BYTES"
        updated.append(replace(asset, status=status))
        entries.append(
            MaterializedAsset(
                asset_id=asset.id,
                slide_id=asset.slide_id,
                status=status,
                required=required,
                source_kind=source_kind,
                fallback=asset.fallback,
                reason=reason,
                byte_sha256=byte_sha256,
                path=path,
                crop_mode=crop_mode,
                focal_safe_zone="center-70-percent",
                replaceable=True,
                provider_route=provider_route,
                provider_model=provider_model,
                provider_manifest=provider_manifest,
            )
        )
    result = AssetMaterialization(
        asset_plan=AssetPlan(
            design_pack_id=asset_plan.design_pack_id,
            assets=tuple(updated),
        ),
        bindings=bindings,
        entries=tuple(entries),
    )
    result.assert_release_ready()
    return result


__all__ = [
    "AssetMaterialization",
    "AssetMaterializationError",
    "ImageGenerator",
    "MaterializedAsset",
    "materialize_asset_plan",
]
